In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
fm = pd.read_csv("famuss.csv")
fm.head(10)

ndrm.ch  drm.ch     sex   age       race  height  weight actn3.r577x     bmi
0      40    40.0  Female  27.0  Caucasian    65.0   199.0          CC  33.112
1      25     0.0    Male  36.0  Caucasian    71.7   189.0          CT  25.845
2      40     0.0  Female  24.0  Caucasian    65.0   134.0          CT  22.296
3     125     0.0  Female  40.0  Caucasian    68.0   171.0          CT  25.998
4      40    20.0  Female  32.0  Caucasian    61.0   118.0          CC  22.293
5      75     0.0  Female  24.0   Hispanic    62.2   120.0          CT  21.805
6     100     0.0  Female  30.0  Caucasian    65.0   134.0          TT  22.296
7    57.1   -14.3  Female  28.0  Caucasian    68.0   162.0          CT  24.629
8    33.3     0.0    Male  27.0   Hispanic    68.2   189.0          CC  28.566
9      20     0.0  Female  30.0  Caucasian    62.2   120.0          CT  21.805

In [4]:
#Extracting the column age
fm['age']

0      27.0
1      36.0
2      24.0
3      40.0
4      32.0
       ... 
591    22.0
592    21.0
593    31.0
594    30.0
595     NaN
Name: age, Length: 596, dtype: float64

In [5]:
#Assigning a variable to column age
df_new = fm['age']
df_new.head(10)

0    27.0
1    36.0
2    24.0
3    40.0
4    32.0
5    24.0
6    30.0
7    28.0
8    27.0
9    30.0
Name: age, dtype: float64

In [8]:
#Changing df_new into an array

df_1 = np.array(df_new)
df_1

array([27., 36., 24., 40., 32., 24., 30., 28., 27., 30., 20., 23., 24.,
       34., 31., 38., 39., 26., 30., 35., 33., 23., 22., 25., 20., 25.,
       24., 26., 38., 31., 22., 22., 26., 27., 31., 31., 35., 33., 21.,
       40., 23., 32., 35., 37., 20., 27., 33., 27., 22., 39., 20., 35.,
       22., 33., 30., 20., 19., 26., 20., 20., 19., 18., 19., 20., 19.,
       19., 19., 34., 20., 21., 25., 21., 20., 22., 23., 17., 18., 18.,
       21., 20., 19., 20., 22., 18., 18., 19., 19., 22., 22., 18., 23.,
       23., 25., 23., 23., 22., 19., 23., 18., 19., 26., 27., 23., 23.,
       28., 25., 19., 19., 28., 22., 26., 26., 20., 19., 18., 24., 23.,
       18., 19., 18., 18., 18., 20., 19., 20., 18., 33., 31., 25., 19.,
       24., 34., 23., 21., 27., 36., 33., 34., 40., 26., 28., 34., 34.,
       28., 27., 29., 22., 29., 38., 28., 34., 21., 27., 39., 28., 30.,
       21., 31., 22., 23., 26., 39., 23., 38., 22., 34., 36., 30., 21.,
       21., 32., 25., 23., 20., 30., 39., 22., 29., 24., 36., 38

In [12]:
#Replacing nan values with o

df_1 = np.nan_to_num(df_1,nan=0)
df_1

array([27., 36., 24., 40., 32., 24., 30., 28., 27., 30., 20., 23., 24.,
       34., 31., 38., 39., 26., 30., 35., 33., 23., 22., 25., 20., 25.,
       24., 26., 38., 31., 22., 22., 26., 27., 31., 31., 35., 33., 21.,
       40., 23., 32., 35., 37., 20., 27., 33., 27., 22., 39., 20., 35.,
       22., 33., 30., 20., 19., 26., 20., 20., 19., 18., 19., 20., 19.,
       19., 19., 34., 20., 21., 25., 21., 20., 22., 23., 17., 18., 18.,
       21., 20., 19., 20., 22., 18., 18., 19., 19., 22., 22., 18., 23.,
       23., 25., 23., 23., 22., 19., 23., 18., 19., 26., 27., 23., 23.,
       28., 25., 19., 19., 28., 22., 26., 26., 20., 19., 18., 24., 23.,
       18., 19., 18., 18., 18., 20., 19., 20., 18., 33., 31., 25., 19.,
       24., 34., 23., 21., 27., 36., 33., 34., 40., 26., 28., 34., 34.,
       28., 27., 29., 22., 29., 38., 28., 34., 21., 27., 39., 28., 30.,
       21., 31., 22., 23., 26., 39., 23., 38., 22., 34., 36., 30., 21.,
       21., 32., 25., 23., 20., 30., 39., 22., 29., 24., 36., 38

In [13]:
#mean of agee

mean = df_1.mean()
mean

24.360738255033556

In [15]:
#Loading the census dataset
cs = pd.read_csv("census.csv")
cs.head(10)

census_year state_fips_code  total_family_income  age     sex  \
0         2000         Florida              14550.0   44    Male   
1         2000         Florida              22800.0   20  Female   
2         2000         Florida                  0.0   20    Male   
3         2000         Florida              23000.0    6  Female   
4         2000         Florida              48000.0   55    Male   
5         2000         Florida              74000.0   43  Female   
6         2000         Florida              23000.0   60  Female   
7         2000         Florida              74000.0   47  Female   
8         2000         Florida              60000.0   54  Female   
9         2000         Florida              14600.0   58  Female   

      race_general          marital_status  total_personal_income  
0  Two major races  Married/spouse present                    0.0  
1            White    Never married/single                13000.0  
2            Black    Never married/single                20000.0  
3            White    Never married/single                    NaN  
4            White  Married/spouse present                36000.0  
5            White  Married/spouse present                27000.0  
6            White  Married/spouse present                11800.0  
7            White  Married/spouse present                48000.0  
8            Black  Married/spouse present                40000.0  
9            White                 Widowed                14600.0

In [16]:
#Extracting column of total_family_income
cs_1 = cs['total_family_income']
cs_1.head

<bound method NDFrame.head of 0      14550.0
1      22800.0
2          0.0
3      23000.0
4      48000.0
        ...   
495     8500.0
496    55400.0
497    15000.0
498        NaN
499    39370.0
Name: total_family_income, Length: 500, dtype: float64>

In [19]:
#Removing nan

cs_1_new = np.array(cs_1)
cs_1_new

array([1.45500e+04, 2.28000e+04, 0.00000e+00, 2.30000e+04, 4.80000e+04,
       7.40000e+04, 2.30000e+04, 7.40000e+04, 6.00000e+04, 1.46000e+04,
       0.00000e+00, 3.70000e+04, 3.20000e+04, 1.13000e+05, 7.69000e+04,
       1.00100e+05, 4.80000e+04, 4.80000e+04, 5.72000e+04, 4.39500e+04,
       4.90000e+04, 3.16000e+04, 5.00900e+04, 6.48000e+04, 9.00000e+04,
       3.83200e+04, 1.03700e+05, 0.00000e+00, 7.07000e+04, 6.48000e+04,
       6.00000e+04, 1.18100e+05, 2.10000e+04, 4.00000e+04, 1.73000e+04,
       6.13000e+04, 0.00000e+00, 6.00000e+03, 3.02700e+04, 8.80000e+03,
       0.00000e+00, 1.65000e+05, 1.55700e+04, 4.86300e+04, 1.30000e+04,
       6.80200e+04, 1.30000e+05, 0.00000e+00,         nan, 1.24000e+04,
       5.04000e+04, 6.50000e+04, 6.29000e+04, 3.12000e+04, 8.17100e+04,
       3.71000e+04, 9.50000e+03, 2.50000e+04, 1.68200e+05, 1.68200e+05,
       5.53000e+04,         nan,         nan, 1.70000e+04, 4.30000e+04,
       1.88000e+04, 1.05000e+05, 4.84000e+04, 5.60000e+04, 8.800

In [21]:
#Removing nan
cs_1_new = np.nan_to_num(cs_1_new)
cs_1_new

array([1.45500e+04, 2.28000e+04, 0.00000e+00, 2.30000e+04, 4.80000e+04,
       7.40000e+04, 2.30000e+04, 7.40000e+04, 6.00000e+04, 1.46000e+04,
       0.00000e+00, 3.70000e+04, 3.20000e+04, 1.13000e+05, 7.69000e+04,
       1.00100e+05, 4.80000e+04, 4.80000e+04, 5.72000e+04, 4.39500e+04,
       4.90000e+04, 3.16000e+04, 5.00900e+04, 6.48000e+04, 9.00000e+04,
       3.83200e+04, 1.03700e+05, 0.00000e+00, 7.07000e+04, 6.48000e+04,
       6.00000e+04, 1.18100e+05, 2.10000e+04, 4.00000e+04, 1.73000e+04,
       6.13000e+04, 0.00000e+00, 6.00000e+03, 3.02700e+04, 8.80000e+03,
       0.00000e+00, 1.65000e+05, 1.55700e+04, 4.86300e+04, 1.30000e+04,
       6.80200e+04, 1.30000e+05, 0.00000e+00, 0.00000e+00, 1.24000e+04,
       5.04000e+04, 6.50000e+04, 6.29000e+04, 3.12000e+04, 8.17100e+04,
       3.71000e+04, 9.50000e+03, 2.50000e+04, 1.68200e+05, 1.68200e+05,
       5.53000e+04, 0.00000e+00, 0.00000e+00, 1.70000e+04, 4.30000e+04,
       1.88000e+04, 1.05000e+05, 4.84000e+04, 5.60000e+04, 8.800

In [23]:
#Calculating mean
mean = cs_1_new.mean()
mean

55688.652

In [28]:
#Calculating standard deviation
std_cs = cs_1_new.std()
std_cs

70276.88940719343

In [31]:
#Using the where function
cs_a = np.where(cs_1_new < 0, cs_1_new,1)
cs_a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [34]:
#Extracting two columns

arr1 = cs['age']
arr2 = cs['total_personal_income']
arr1
arr2

0      44
1      20
2      20
3       6
4      55
       ..
495    68
496    12
497    60
498    60
499    47
Name: age, Length: 500, dtype: int64

In [43]:
#Removing nan values from arrays

arr1 = np.nan_to_num(arr1)
arr2 = np.nan_to_num(arr2)
#arr1
arr2


array([ 0.0000e+00,  1.3000e+04,  2.0000e+04,  0.0000e+00,  3.6000e+04,
        2.7000e+04,  1.1800e+04,  4.8000e+04,  4.0000e+04,  1.4600e+04,
        2.3000e+04,  3.7000e+04,  3.2000e+04,  0.0000e+00,  6.0000e+03,
        1.6100e+04,  1.2000e+04,  0.0000e+00,  2.0000e+04,  4.8000e+03,
        2.8000e+04,  3.1600e+04,  0.0000e+00,  4.9300e+04,  0.0000e+00,
        3.4320e+04,  0.0000e+00,  8.4000e+03,  3.7000e+03,  4.8000e+03,
        5.3000e+04,  7.5000e+03,  6.0000e+03,  0.0000e+00,  4.8000e+03,
        3.5000e+04,  2.0000e+03,  0.0000e+00,  2.4250e+04,  8.8000e+03,
        1.7000e+04,  1.2300e+05,  1.5570e+04,  1.5830e+04,  0.0000e+00,
        0.0000e+00,  6.4000e+04,  1.7500e+04,  0.0000e+00,  0.0000e+00,
        4.0000e+03,  0.0000e+00,  2.0000e+03,  1.0000e+04,  0.0000e+00,
        3.7100e+04,  1.8000e+03,  2.5000e+04,  1.2160e+05,  0.0000e+00,
        5.5300e+04,  2.0000e+03,  0.0000e+00,  0.0000e+00,  0.0000e+00,
        0.0000e+00,  1.0500e+05,  0.0000e+00,  0.0000e+00,  0.00

In [42]:
#Using functions for performing element-wise operations on Numpy arrays
arr_new = sum(arr1,arr2)
arr_new

array([ 17649.,  30649.,  37649.,  17649.,  53649.,  44649.,  29449.,
        65649.,  57649.,  32249.,  40649.,  54649.,  49649.,  17649.,
        23649.,  33749.,  29649.,  17649.,  37649.,  22449.,  45649.,
        49249.,  17649.,  66949.,  17649.,  51969.,  17649.,  26049.,
        21349.,  22449.,  70649.,  25149.,  23649.,  17649.,  22449.,
        52649.,  19649.,  17649.,  41899.,  26449.,  34649., 140649.,
        33219.,  33479.,  17649.,  17649.,  81649.,  35149.,  17649.,
        17649.,  21649.,  17649.,  19649.,  27649.,  17649.,  54749.,
        19449.,  42649., 139249.,  17649.,  72949.,  19649.,  17649.,
        17649.,  17649.,  17649., 122649.,  17649.,  17649.,  17649.,
        37549.,  17649.,  39649.,  18369.,  72649.,  55649.,  34949.,
        17649.,  31849.,  32149.,  17649.,  17649.,  61653.,  60649.,
        17649.,  20649.,  65599.,  28849.,  32949.,  17649.,  44649.,
        27649.,  69749.,  35149.,  17649.,  17649.,  42649., 151649.,
        17649., 1326

In [45]:
##using the add() function

added_arr = np.add(arr1,arr2)
added_arr

array([ 4.40000e+01,  1.30200e+04,  2.00200e+04,  6.00000e+00,
        3.60550e+04,  2.70430e+04,  1.18600e+04,  4.80470e+04,
        4.00540e+04,  1.46580e+04,  2.30330e+04,  3.70510e+04,
        3.20620e+04,  8.00000e+00,  6.02500e+03,  1.61440e+04,
        1.20280e+04,  1.00000e+00,  2.00310e+04,  4.86900e+03,
        2.80310e+04,  3.16800e+04,  2.00000e+00,  4.93470e+04,
        1.20000e+01,  3.43670e+04,  8.00000e+00,  8.46700e+03,
        3.71700e+03,  4.86900e+03,  5.30550e+04,  7.51800e+03,
        6.06600e+03,  5.80000e+01,  4.82100e+03,  3.50520e+04,
        2.01800e+03,  2.00000e+00,  2.42760e+04,  8.88200e+03,
        1.70460e+04,  1.23063e+05,  1.56530e+04,  1.58650e+04,
        1.00000e+00,  2.00000e+00,  6.40540e+04,  1.75360e+04,
        2.80000e+01,  7.00000e+00,  4.02100e+03,  1.00000e+00,
        2.01700e+03,  1.00290e+04,  1.40000e+01,  3.71330e+04,
        1.81600e+03,  2.50400e+04,  1.21634e+05,  6.00000e+00,
        5.53490e+04,  2.01700e+03,  3.70000e+01,  2.000

In [46]:
##Subtracting the two arrays

subtracted_array = np.subtract(arr1,arr2)
subtracted_array

array([ 4.40000e+01, -1.29800e+04, -1.99800e+04,  6.00000e+00,
       -3.59450e+04, -2.69570e+04, -1.17400e+04, -4.79530e+04,
       -3.99460e+04, -1.45420e+04, -2.29670e+04, -3.69490e+04,
       -3.19380e+04,  8.00000e+00, -5.97500e+03, -1.60560e+04,
       -1.19720e+04,  1.00000e+00, -1.99690e+04, -4.73100e+03,
       -2.79690e+04, -3.15200e+04,  2.00000e+00, -4.92530e+04,
        1.20000e+01, -3.42730e+04,  8.00000e+00, -8.33300e+03,
       -3.68300e+03, -4.73100e+03, -5.29450e+04, -7.48200e+03,
       -5.93400e+03,  5.80000e+01, -4.77900e+03, -3.49480e+04,
       -1.98200e+03,  2.00000e+00, -2.42240e+04, -8.71800e+03,
       -1.69540e+04, -1.22937e+05, -1.54870e+04, -1.57950e+04,
        1.00000e+00,  2.00000e+00, -6.39460e+04, -1.74640e+04,
        2.80000e+01,  7.00000e+00, -3.97900e+03,  1.00000e+00,
       -1.98300e+03, -9.97100e+03,  1.40000e+01, -3.70670e+04,
       -1.78400e+03, -2.49600e+04, -1.21566e+05,  6.00000e+00,
       -5.52510e+04, -1.98300e+03,  3.70000e+01,  2.000

In [47]:
##Multiplying the array

multiple_array = np.multiply(arr1,arr2)
multiple_array

array([ 0.00000e+00,  2.60000e+05,  4.00000e+05,  0.00000e+00,
        1.98000e+06,  1.16100e+06,  7.08000e+05,  2.25600e+06,
        2.16000e+06,  8.46800e+05,  7.59000e+05,  1.88700e+06,
        1.98400e+06,  0.00000e+00,  1.50000e+05,  7.08400e+05,
        3.36000e+05,  0.00000e+00,  6.20000e+05,  3.31200e+05,
        8.68000e+05,  2.52800e+06,  0.00000e+00,  2.31710e+06,
        0.00000e+00,  1.61304e+06,  0.00000e+00,  5.62800e+05,
        6.29000e+04,  3.31200e+05,  2.91500e+06,  1.35000e+05,
        3.96000e+05,  0.00000e+00,  1.00800e+05,  1.82000e+06,
        3.60000e+04,  0.00000e+00,  6.30500e+05,  7.21600e+05,
        7.82000e+05,  7.74900e+06,  1.29231e+06,  5.54050e+05,
        0.00000e+00,  0.00000e+00,  3.45600e+06,  6.30000e+05,
        0.00000e+00,  0.00000e+00,  8.40000e+04,  0.00000e+00,
        3.40000e+04,  2.90000e+05,  0.00000e+00,  1.22430e+06,
        2.88000e+04,  1.00000e+06,  4.13440e+06,  0.00000e+00,
        2.70970e+06,  3.40000e+04,  0.00000e+00,  0.000

In [55]:
##uSING THE WHERE() FUNCTION ON MULTIPLE_ARRAY
newest_array = np.where(multiple_array <1, multiple_array, 1)
newest_array

array([ 0.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,  1.000e+00,
        1.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,
        1.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,  1.000e+00,
        1.000e+00,  1.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,
        1.000e+00,  1.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,
        1.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,
        1.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,  1.000e+00,
        1.000e+00,  1.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,
        1.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        0.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,
        1.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        1.000e+00,  1.000e+00,  1.000e+00,  1.000e+00,  0.000e+00,
        1.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        1.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,  1.000e

In [56]:
##Adding two new arrays together

ar = np.add(multiple_array,subtracted_array)
ar

array([ 4.4000000e+01,  2.4702000e+05,  3.8002000e+05,  6.0000000e+00,
        1.9440550e+06,  1.1340430e+06,  6.9626000e+05,  2.2080470e+06,
        2.1200540e+06,  8.3225800e+05,  7.3603300e+05,  1.8500510e+06,
        1.9520620e+06,  8.0000000e+00,  1.4402500e+05,  6.9234400e+05,
        3.2402800e+05,  1.0000000e+00,  6.0003100e+05,  3.2646900e+05,
        8.4003100e+05,  2.4964800e+06,  2.0000000e+00,  2.2678470e+06,
        1.2000000e+01,  1.5787670e+06,  8.0000000e+00,  5.5446700e+05,
        5.9217000e+04,  3.2646900e+05,  2.8620550e+06,  1.2751800e+05,
        3.9006600e+05,  5.8000000e+01,  9.6021000e+04,  1.7850520e+06,
        3.4018000e+04,  2.0000000e+00,  6.0627600e+05,  7.1288200e+05,
        7.6504600e+05,  7.6260630e+06,  1.2768230e+06,  5.3825500e+05,
        1.0000000e+00,  2.0000000e+00,  3.3920540e+06,  6.1253600e+05,
        2.8000000e+01,  7.0000000e+00,  8.0021000e+04,  1.0000000e+00,
        3.2017000e+04,  2.8002900e+05,  1.4000000e+01,  1.1872330e+06,
      

In [57]:
##MANIPULATINGTHE AGE COLUMN

df = cs['age']
df

0      44
1      20
2      20
3       6
4      55
       ..
495    68
496    12
497    60
498    60
499    47
Name: age, Length: 500, dtype: int64

In [59]:
#Converting column to dataframe

df_1 = np.array(df)
df_1

array([44, 20, 20,  6, 55, 43, 60, 47, 54, 58, 33, 51, 62,  8, 25, 44, 28,
        1, 31, 69, 31, 80,  2, 47, 12, 47,  8, 67, 17, 69, 55, 18, 66, 58,
       21, 52, 18,  2, 26, 82, 46, 63, 83, 35,  1,  2, 54, 36, 28,  7, 21,
        1, 17, 29, 14, 33, 16, 40, 34,  6, 49, 17, 37,  2, 40, 10, 61, 24,
       23, 16, 36,  7, 32, 19, 81, 47, 72,  2, 46, 27,  2, 10, 30, 39, 12,
       73, 40, 60, 43,  7, 40, 65, 80, 46,  3,  6, 26, 58, 48, 62, 22, 52,
       60,  3, 21, 30, 58,  5, 20, 18, 45, 20, 28, 19, 60, 75, 22, 58, 52,
       58, 24, 46, 43, 41, 47, 40, 24, 13, 41,  4, 77, 60,  7, 35, 52, 72,
       31, 45, 79, 16, 41, 37, 26,  8,  6,  8, 60,  4, 22, 49,  4, 52, 47,
       39, 34, 23, 49, 21, 56, 62, 40, 62, 37, 50, 20, 15, 39, 87, 78, 35,
       48, 41, 51, 24, 21, 25, 51, 25, 32, 40, 29, 54, 69,  2, 40,  6, 38,
       46, 54, 73, 38, 31, 32, 14, 38, 46, 25, 35, 40, 17, 55, 70, 24,  6,
       29, 52, 56, 69, 15, 65, 50, 11, 37, 12, 40, 21, 75, 53, 10, 27, 33,
        2, 57, 12, 21, 45

In [60]:
##Getting mean

mean = df_1.mean()
mean

35.298

In [65]:
#Getting standard deviation
standard_dev = df_1.std()
standard_dev

21.79030050274663

In [66]:
#Getting sum
sum = df_1.sum()
sum

17649